import React, { useState, useContext } from 'react';
import InfoIcon from '../../../assets/icons/info.png';
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/css';
import { ModalContext } from '../../../UtilsProvider/StockPageModal';
import nextArrow from '../../../assets/icons/nextArrow.png';
import prevArrow from '../../../assets/icons/prevArrow.png';
import Image from 'next/image'

import CashFlowCard from '../../../elements/CompanyFinCards/CashFlowCard/CashFlowCard';
import BalanceSheetCard from '../../../elements/CompanyFinCards/BalanceSheetCard/BalanceSheetCard';
import NetProfitCard from '../../../elements/CompanyFinCards/NetProfitCard/NetProfitCard';
import RevenueCard from '../../../elements/CompanyFinCards/RevenueCard/RevenueCard';

const modalData = [
    {
        heading: `Net profit`,
        details: `Net profit is the amount of money your business earns after deducting all operating, interest, and tax expenses over a given period of time`
    }, {
        heading: `Revenue`,
        details: `Revenue is the total amount of income generated by the sale of goods or services related to the company's primary operations`
    }, {
        heading: `Cash flow`,
        details: `Cashflow means the net amount of cash and cash equivalents being transferred in and out of the company`
    }
]

function CompanyFinancial({ name }) {
    const modal = useContext(ModalContext)

    const [compFinIndex, setCompFinIndex] = useState(0);
    const [swiper, setSwiper] = useState(0);
    const slideTo = (index) => swiper.slideTo(index);


    const openModalHandler = () => {
        modal.setTitle('Company financials')
        modal.setModaldata(modalData)
        modal.setModal(true);
    }

    const handleSlide = (n) => {
        setCompFinIndex(n);
        slideTo(n);
    }

    return (<div>
        <div className='relative'>
            <div id='company-financial' className='absolute -top-44' />

            <button className='hidden md:flex p-[6px] w-[32px] h-[32px] absolute -top-0 right-20 bg-[#e8edf5] hover:bg-[#b9ceeb] rounded-full' onClick={() => swiper.slidePrev()}>
                <Image src={prevArrow} alt="close" className='h-full mx-auto' />
            </button>
            <button className='hidden md:flex p-[6px] w-[32px] h-[32px] absolute -top-0 right-8 bg-[#e8edf5] hover:bg-[#b9ceeb] rounded-full' onClick={() => swiper.slideNext()}>
                <Image src={nextArrow} alt="close" className='h-full mx-auto' />
            </button>

            <div className='font-Inter text-[16px] text-black flex flex-row mx-4 mt-6 mb-4 font-semibold  md:mt-10'>
                <div className='mr-4'>Company financials</div>
                <button
                    className='w-[16px] h-[16px] self-center'
                    onClick={openModalHandler}
                >
                    <Image src={InfoIcon} alt='info' className='w-[16px] h-[16px] self-center' />
                </button>
            </div>
            <div
                className='md:hidden font-Inter text-[12px] flex flex-row justify-between my-4 overflow-x-auto no-scrollbar swiper-no-swiping'>
                <button
                    className={compFinIndex === 0 ?
                        'rounded-[19px] px-3 py-1 bg-[#EFF6FF] text-[#00439D] outline-none font-semibold min-w-[90px] ml-2' :
                        'rounded-[19px] px-3 py-1 font-medium min-w-[90px] ml-2'}
                    onClick={() => handleSlide(0)}
                >
                    Net profit
                </button>
                <button
                    className={compFinIndex === 1 ?
                        'rounded-[19px] px-3 py-1 bg-[#EFF6FF] text-[#00439D] outline-none font-semibold ' :
                        'rounded-[19px] px-3 py-1 font-medium '}
                    onClick={() => handleSlide(1)}
                >
                    Revenue
                </button>
                <button
                    className={compFinIndex === 2 ?
                        'rounded-[19px] px-3 py-1 bg-[#EFF6FF] text-[#00439D] outline-none font-semibold min-w-[132px]' :
                        'rounded-[19px] px-3 py-1 font-medium min-w-[132px] '}
                    onClick={() => handleSlide(2)}
                >
                    Balance sheet
                </button>
                <button
                    className={compFinIndex === 3 ?
                        'rounded-[19px] px-3 py-1 bg-[#EFF6FF] text-[#00439D] outline-none font-semibold min-w-[97px]' :
                        'rounded-[19px] px-3 py-1 font-medium min-w-[97px]'}
                    onClick={() => handleSlide(3)}
                >
                    Cash flow
                </button>
            </div>
            <div className="mt-8 mb-1 flex flex-row overflow-x-auto no-scrollbar">
                <Swiper
                    spaceBetween={-10}
                    slidesPerView={1.1}
                    breakpoints={{
                        768: {
                            slidesPerView: 2.8
                        },
                    }}
                    onSlideChange={(e) => setCompFinIndex(e.activeIndex)}
                    onSwiper={setSwiper}
                >
                    <SwiperSlide>
                        <NetProfitCard
                            name={name}
                            number={1}
                            indicator={'NP'}
                        />
                    </SwiperSlide>
                    <SwiperSlide>
                        <RevenueCard
                            name={name}
                            number={2}
                            indicator={'RE'}
                        />
                    </SwiperSlide>
                    <SwiperSlide>
                        <BalanceSheetCard
                            name={name}
                            number={3}
                            indicator={'balance-sheet'}
                        />
                    </SwiperSlide>
                    <SwiperSlide>
                        <CashFlowCard
                            name={name}
                            number={4}
                            indicator={'CF'}
                        />
                    </SwiperSlide>
                </Swiper>
            </div>
        </div>
    </div>
    )
}

export default CompanyFinancial;
